#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'polar-h10==0.0.1','console_scripts','polar_h10_node'
__requires__ = 'polar-h10==0.0.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('polar-h10==0.0.1', 'console_scripts', 'polar_h10_node')()
    )
